language: node_js
node_js:
  - "4"
services:
  - mongodb
addons:
  apt:
    packages:
      - mongodb-org-tools
before_script:
  - mongoimport --db tc --collection cards --type json --file mock-db.json
after_success: npm run coverage